---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdbot-deployment
  labels:
    app: birdbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birdbot
  template:
    metadata:
      labels:
        app: birdbot
    spec:
      serviceAccountName: birdbot
      containers:
      - name: birdbot
        image: unixbird/birdbot:latest
        imagePullPolicy: Always
        env:
         - name: TOKEN
           value: 'YOURSECRETTOKEN'# You NEED to insert your own token or else the pod will crash
         - name: PREFIX
           value: '!'
         - name: HOSTNAME
           value: 'birdbot'
