---
# Service account the client will use to reset the deployment,
# Change the name and namespace to whatever you need but make sure they all match. In this example this service account only has access
# to rollout the librespeed-deployment
kind: ServiceAccount
apiVersion: v1
metadata:
  name: birdbot
  namespace: default
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: birdbot
  namespace: default
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["librespeed-deployment"]
    verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
                                             # if you want to use `rollout status`
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: birdbot
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: birdbot
subjects:
  - kind: ServiceAccount
    name: birdbot
    namespace: default
